version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - '7000:7000'

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - '3000:3000'
